version: "3.8"

services:
  backend:
    build: ./backend
    container_name: node-backend
    ports:
      - "5000:5000" # backend exposed on localhost:5000
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo # example if backend needs a DB
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "3000:80" # frontend exposed on localhost:3000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  # Optional: MongoDB (only if your backend needs it)
  mongo:
    image: mongo:6
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
